### ISSUE TITLE
invalid literal for int() with base error

### ISSUE THREAD

**Issue by LHG-GG** [xjtu-omics/HiCAT#10]
Hi,

could you help with https://github.com/865699871/HiCAT/issues/3

**Comment by 865699871** [comment]
You can rename the input sequence and don't use :: or -.

**Comment by LHG-GG** [comment]
I have removed everything like you said, the error still remains
```
Prepared reads
100%: Aligned chr22_Mat
2024-02-22 13:04:50,343 - StringDecomposer - INFO - Saved raw decomposition to ./HiCAT_out/final_decomposition_raw.tsv
2024-02-22 13:04:50,542 - StringDecomposer - INFO - Transforming raw alignments...
2024-02-22 13:05:15,755 - StringDecomposer - INFO - Transformation finished. Results can be found in ./HiCAT_out/final_decomposition.tsv
2024-02-22 13:05:15,758 - StringDecomposer - INFO - Thank you for using StringDecomposer!
Run HiCAT HOR

python /home/sarashettp/miniforge3/envs/hica/bin/HiCAT_HOR.py -d ./HiCAT_out/final_decomposition.tsv -b ./HiCAT_out/input_fasta.1.fa -o ./HiCAT_out -s 0.94 -st 0.005 -m 40 -sp 5 -sn 10 -t 50
start
build block sequence and read base sequence
calculate ed distance
ed distance thread: 50
Traceback (most recent call last):
  File "/home/sarashettp/miniforge3/envs/hica/bin/HiCAT_HOR.py", line 1589, in <module>
    main()
  File "/home/sarashettp/miniforge3/envs/hica/bin/HiCAT_HOR.py", line 1495, in main
    edit_distance_matrix, block_name_index = calculateED(block_sequence, base_sequence,thread)
  File "/home/sarashettp/miniforge3/envs/hica/bin/HiCAT_HOR.py", line 62, in calculateED
    split_base_sequence = base_sequence[int(items[1]):int(items[2])]
ValueError: invalid literal for int() with base 10: 'Mat'

```

**Comment by 865699871** [comment]
I guess may be '_'. If there is still problem you can send us your input fa file. E-mail is zym81666881@stu.xjtu.edu.cn.
